name: Continuous Integration

on:
  push:
    branches: master
    paths:
      - 'cmd/konvey/**'
      - 'internal/konvey/**'
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  ci:
    uses: kowabunga-cloud/workflows/.github/workflows/go-ci.yml@master
    secrets: inherit
