name: Vulnerabilities Check

on:
  push:
    branches: master
    paths:
      - 'cmd/konvey/**'
      - 'internal/konvey/**'
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  vuln:
    uses: kowabunga-cloud/workflows/.github/workflows/go-vuln.yml@master
    secrets: inherit
